server:
  port: 8080

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      someShared:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 10

      instances:
        backendA:
          baseConfig: default
          waitDurationInOpenState: 5000
        backendB:
          baseConfig: someShared
